---
- name: deploy on tomcat
  hosts: all
  become: true
  remote_user: apx14

  tasks:
      - name: deploy war
        copy:
            src: target/myapp-g15.war
            dest: /opt/tomcat/webapps/